pluginManagement {
    plugins {
        id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
        id 'fabric-loom' version "${loom_version}" apply false
        id "maven-publish" apply false
        id 'com.palantir.git-version' version "${gradle_git_rev_version}" apply false
    }
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include 'shared'
include 'versioned:sc26.1'
include 'versioned:sc26.2'
