# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build project
on:
  push:
    branches:
      - main
      - legacy
      - 'port/**'
      - 'workflow/**'
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        java: [ 25 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Java ${{ matrix.java }} setup
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Gradle build
        run: ./gradlew build

      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Artifacts
          path: build/libs/
